// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi98M3hAKwXg69oP_WICa3p9qxLaFVe2E',
    appId: '1:813442798533:web:40487364dc475c83fef1ac',
    messagingSenderId: '813442798533',
    projectId: 'fseg-1c70b',
    databaseURL: 'https://fseg-1c70b-default-rtdb.firebaseio.com/',
    authDomain: 'fseg-1c70b.firebaseapp.com',
    storageBucket: 'fseg-1c70b.appspot.com',
    measurementId: 'G-RJGQCCRH5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkwKlVH5eLBQx2Clkm_MK9pQgICPqUczs',
    appId: '1:813442798533:android:728faebb916deff8fef1ac',
    messagingSenderId: '813442798533',
    projectId: 'fseg-1c70b',
    storageBucket: 'fseg-1c70b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0cxvcSzDvoDpjV_1oaVEgjOooHdsznrc',
    appId: '1:813442798533:ios:f2690aaf89dcf3aefef1ac',
    messagingSenderId: '813442798533',
    projectId: 'fseg-1c70b',
    storageBucket: 'fseg-1c70b.appspot.com',
    iosBundleId: 'com.example.fseg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0cxvcSzDvoDpjV_1oaVEgjOooHdsznrc',
    appId: '1:813442798533:ios:f2690aaf89dcf3aefef1ac',
    messagingSenderId: '813442798533',
    projectId: 'fseg-1c70b',
    storageBucket: 'fseg-1c70b.appspot.com',
    iosBundleId: 'com.example.fseg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi98M3hAKwXg69oP_WICa3p9qxLaFVe2E',
    appId: '1:813442798533:web:f79177e75038a532fef1ac',
    messagingSenderId: '813442798533',
    projectId: 'fseg-1c70b',
    authDomain: 'fseg-1c70b.firebaseapp.com',
    storageBucket: 'fseg-1c70b.appspot.com',
    measurementId: 'G-SETFN9WGSL',
  );
}
