import 'package:flutter/material.dart';

import 'Femme.dart';

void main() {
  runApp(const HomePage());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AndroidSmall2(),
        ]),
      ),
    );
  }
}

class AndroidSmall2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 640,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 21,
                top: 72,
                child: Container(
                  width: 319,
                  height: 122,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 88.52,
                          height: 82.51,
                          decoration: ShapeDecoration(
                            color: Color(0xE8593EAB),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(15),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 115.53,
                        top: 0,
                        child: Container(
                          width: 88.52,
                          height: 82.51,
                          decoration: ShapeDecoration(
                            color: Color(0x77D9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(15),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 230.48,
                        top: 0,
                        child: Container(
                          width: 88.52,
                          height: 82.51,
                          decoration: ShapeDecoration(
                            color: Color(0x77D9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(15),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 2.87,
                        top: 0,
                        child: Container(
                          width: 83.34,
                          height: 80.74,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/83x81"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 122.43,
                        top: 4.13,
                        child: Container(
                          width: 71.85,
                          height: 72.49,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/72x72"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 239.11,
                        top: 5.89,
                        child: Container(
                          width: 71.85,
                          height: 72.49,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/72x72"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 25.86,
                        top: 100.78,
                        child: SizedBox(
                          width: 62.65,
                          height: 21.22,
                          child: Text(
                            'All',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Aclonica',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 127.03,
                        top: 101.96,
                        child: SizedBox(
                          width: 95.99,
                          height: 18.86,
                          child: Text(
                            'Burger',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Aclonica',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 241.98,
                        top: 100.78,
                        child: SizedBox(
                          width: 65.52,
                          height: 21.22,
                          child: Text(
                            'Pizza',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Aclonica',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 210,
                child: Container(
                  width: 321,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 321,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: Color(0xA5D9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(40),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 74.03,
                        top: 14.03,
                        child: SizedBox(
                          width: 130.71,
                          height: 31.17,
                          child: Text(
                            'Search',
                            style: TextStyle(
                              color: Colors.black.withOpacity(0.5),
                              fontSize: 24,
                              fontFamily: 'Abel',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 22.56,
                        top: 14.03,
                        child: Container(
                          width: 27.76,
                          height: 31.17,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [

                              ]),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 22,
                child: SizedBox(
                  width: 252,
                  height: 70,
                  child: Text(
                    'Menu',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 32,
                      fontFamily: 'Aclonica',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 298,
                child: SizedBox(
                  width: 252,
                  height: 70,
                  child: Text(
                    'Popular',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 32,
                      fontFamily: 'Aclonica',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 9,
                top: 344,
                child: Container(
                  width: 161,
                  height: 194,
                  child: GestureDetector(
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (context) => Product()),
                      );
                    },
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 161,
                          height: 194,
                          decoration: ShapeDecoration(
                            color: Color(0x7CD9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),

                      ),
                      Positioned(
                        left: 32.78,
                        top: 22.74,
                        child: Container(
                          width: 91.06,
                          height: 87.41,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/91x87"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 27.68,
                        top: 118.67,
                        child: GestureDetector(
                          onTap: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(builder: (context) => Product()),
                            );
                          },
                        child: SizedBox(
                          width: 131.86,
                          height: 32.69,
                          child: Text(
                            'Beef Burger',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Abril Fatface',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                        ),
                      ),
                      Positioned(
                        left: 14.57,
                        top: 155.63,
                        child: SizedBox(
                          width: 83.05,
                          height: 22.03,
                          child: Text(
                            '16 DT',
                            style: TextStyle(
                              color: Color(0xFFC9AA05),
                              fontSize: 24,
                              fontFamily: 'Abril Fatface',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 112.19,
                        top: 148.52,
                        child: Container(
                          width: 34.24,
                          height: 34.82,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [

                              ]),
                        ),
                      ),
                    ],
                  ),
                ),
                ),
              ),
              Positioned(
                left: 190,
                top: 344,
                child: Container(
                  width: 161,
                  height: 194,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 161,
                          height: 194,
                          decoration: ShapeDecoration(
                            color: Color(0x7CD9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 32.78,
                        top: 22.74,
                        child: Container(
                          width: 91.06,
                          height: 87.41,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/91x87"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 27.68,
                        top: 118.67,
                        child: SizedBox(
                          width: 131.86,
                          height: 32.69,
                          child: Text(
                            'Cheken Burger',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Abril Fatface',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 14.57,
                        top: 155.63,
                        child: SizedBox(
                          width: 83.05,
                          height: 22.03,
                          child: Text(
                            '13 DT',
                            style: TextStyle(
                              color: Color(0xFFC9AA05),
                              fontSize: 24,
                              fontFamily: 'Abril Fatface',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 112.19,
                        top: 148.52,
                        child: Container(
                          width: 34.24,
                          height: 34.82,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [

                              ]),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 569,
                child: Container(
                  width: 360,
                  height: 71,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(20),
                        topRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 578,
                child: Container(
                  width: 45,
                  height: 45,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(children: [

                      ]),
                ),
              ),
              Positioned(
                left: 208,
                top: 578,
                child: Container(
                  width: 45,
                  height: 45,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(children: [

                      ]),
                ),
              ),
              Positioned(
                left: 296,
                top: 578,
                child: Container(
                  width: 45,
                  height: 45,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(children: [

                      ]),
                ),
              ),
              Positioned(
                left: 116,
                top: 578,
                child: Container(
                  width: 45,
                  height: 45,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(children: [

                      ]),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}